- src/main/java/com/dnd12th_4/pickitalki/domain/member/Member.java
- src/main/resources/schema.sql
로그인 기능에서 멤버의 도메인 약간 수정
멤버의 테이블명 -> members
schema.sql의 create문 현재 도메인에 맞게 변경
> feat: 로그인 기능 배포 위한 수정

- src/main/java/com/dnd12th_4/pickitalki/controller/channel/ChannelController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/dto/ChannelSpecificResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionCreateRequest.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionCreateResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/TodayQuestionResponse.java
- src/main/java/com/dnd12th_4/pickitalki/domain/BaseEntity.java
- src/main/java/com/dnd12th_4/pickitalki/domain/channel/Channel.java
- src/main/java/com/dnd12th_4/pickitalki/domain/question/Question.java
- src/main/java/com/dnd12th_4/pickitalki/domain/question/QuestionRepository.java
- src/main/java/com/dnd12th_4/pickitalki/service/channel/ChannelService.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
- src/main/resources/schema.sql
Post - "/api/channels/{channelId}/questions" :  해당 채널에 질문을 생성하는 API, requestBody에 질문내용과 익명여부, 익명이름 필요 
Get - "/api/channels/{channelId}/questions/today" : 오늘의 질문 조회 -> 존재하지 않는다면 content=null, isExist=false로 세팅되어 응답
Get - "/api/channels/{channelId}/questions/all": 해당 채널의 모든 질문 조회
> 질문 생성,조회 기능 구현

- src/main/java/com/dnd12th_4/pickitalki/common/interceptor/JwtInterceptor.java
> [fix]: cors요청은 인터셉터에서 통과하도록 수정

- src/main/java/com/dnd12th_4/pickitalki/controller/channel/ChannelController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/dto/ChannelShowAllResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/dto/ChannelSpecificResponse.java
- src/main/java/com/dnd12th_4/pickitalki/domain/channel/Channel.java
- src/main/java/com/dnd12th_4/pickitalki/service/channel/ChannelService.java
- src/main/resources/schema.sql
아래 요청 해결
채널 조회를 채널 id로 조회하도록 수정 
채널조회 응답에 채널Id도 포함하도록 수정
> [Refactor] 채널 조회 API의 url과 응답수정

- src/main/java/com/dnd12th_4/pickitalki/domain/member/Member.java
- src/main/java/com/dnd12th_4/pickitalki/service/login/KakaoUserService.java
- src/main/resources/schema.sql
> [refactor] : 카카오 로그인시 유저닉네임 null 가능하게 변경

- src/main/java/com/dnd12th_4/pickitalki/controller/login/TokenAuthController.java
- src/main/java/com/dnd12th_4/pickitalki/service/login/KaKaoSignUpService.java
[refactor] : refreshToken requst를 Autoriation 형태로 받는걸로 바꿈
기존에는 쿠키형태로 refreshToken을 발급 받았는데 프론트와 논의 후
Header 값에 Authrization에 넣어 달라는 부탁을 받아서 그 부분 리팩터링 진행했습니다.
> [refactor] : refreshToken requst를 Autoriation 형태로 받는걸로 바꿈

- src/main/java/com/dnd12th_4/pickitalki/common/config/AppConfig.java
- src/main/java/com/dnd12th_4/pickitalki/controller/answer/AnswerController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/ChannelController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/ChannelControllerEnums.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/dto/response/ChannelJoinResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/dto/response/ChannelMemberResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/dto/response/ChannelMemberStatusResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/dto/response/ChannelResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/dto/response/ChannelShowAllResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/dto/response/ChannelSpecificResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/dto/response/MemberCodeNameResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/member/MemberController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/member/ProfileImageController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/member/dto/ChannelFriendResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/member/dto/ImageResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/member/dto/MemberResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/member/dto/MemberUpdateRequest.java
- src/main/java/com/dnd12th_4/pickitalki/controller/member/dto/MyChannelMemberResponse.java
- src/main/java/com/dnd12th_4/pickitalki/domain/channel/ChannelMemberLevel.java
- src/main/java/com/dnd12th_4/pickitalki/domain/member/Member.java
- src/main/java/com/dnd12th_4/pickitalki/presentation/exceptionhandler/ApiExceptionHandler.java
- src/main/java/com/dnd12th_4/pickitalki/presentation/exceptionhandler/GlobalExceptionHandler.java
- src/main/java/com/dnd12th_4/pickitalki/service/answer/AnswerService.java
- src/main/java/com/dnd12th_4/pickitalki/service/channel/ChannelService.java
- src/main/java/com/dnd12th_4/pickitalki/service/login/MemberService.java
- src/main/resources/application.yml
> [feat] 채널 조회 API에 대한 수정 - 초대코드 응답 추가, 쿼리 파라미터로 조회받기

- src/main/java/com/dnd12th_4/pickitalki/common/dto/request/PageParamRequest.java
- src/main/java/com/dnd12th_4/pickitalki/common/dto/response/PageParamResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/answer/AnswerController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/answer/dto/response/AnswerShowAllResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/answer/dto/response/AnswerWriteResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/login/KakaoAuthExchangeController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/login/TokenAuthController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/login/dto/response/RefreshTokenResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/login/dto/response/UserResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/dto/QuestionUpdateRequest.java
- src/main/java/com/dnd12th_4/pickitalki/domain/answer/AnswerRepository.java
- src/main/java/com/dnd12th_4/pickitalki/domain/question/QuestionRepository.java
- src/main/java/com/dnd12th_4/pickitalki/service/answer/AnswerService.java
- src/main/java/com/dnd12th_4/pickitalki/service/login/KakaoUserService.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
기존 파라미터는 channelId를 사용하지 않았습니다. 
프론트 측에서 이미 코드를 작성 완료?? 이런 형태로 하셨는지 channelId를 다시 넣은 형태로 개발 부탁드려서
일단은 그렇게 진행했습니다.
> Refactor question 파라미터 관련 변경 요청이 있어급하게 바꾸겠습니다.

- src/main/java/com/dnd12th_4/pickitalki/controller/login/dto/response/KakaoUserDto.java
> [chore] : KakaoUserDto 경로변경

- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionController.java
> [chore] : 파라미터 변경

- src/main/java/com/dnd12th_4/pickitalki/common/token/JwtProvider.java
- src/main/java/com/dnd12th_4/pickitalki/controller/login/KakaoAuthExchangeController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/login/dto/response/RefreshTokenResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/login/dto/response/UserResponse.java
> [chore] : expiredAccessToken 만료기간 초단위로 변경

- src/main/java/com/dnd12th_4/pickitalki/common/dto/request/PageParamRequest.java
- src/main/java/com/dnd12th_4/pickitalki/common/pagination/Pagination.java
- src/main/java/com/dnd12th_4/pickitalki/controller/answer/AnswerController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/ChannelController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/ChannelMemberController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/login/dto/response/NewMemberStatus.java
- src/main/java/com/dnd12th_4/pickitalki/controller/member/MemberController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionController.java
> Feat pagination PageParamRequest swagger에서 안보이게 설정했습니다.

- src/main/java/com/dnd12th_4/pickitalki/domain/channel/Channel.java
- src/main/java/com/dnd12th_4/pickitalki/domain/channel/ChannelMember.java
- src/main/java/com/dnd12th_4/pickitalki/domain/question/Question.java
- src/main/java/com/dnd12th_4/pickitalki/service/channel/ChannelService.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
[fix] 채널을 삭제하거나 채널멤버를 삭제시 삭제가 안되는 오류가 있었습니다.
cascade에 REMOVE 추가했고 
고아겍체 true 값으로 변경했습니다.
추가적으로 프론트 측에서 개발기간동안 하루에 질문 한개의 제한 조건을 풀어달라고 요청하여
아래의 사진 3곳을 잠시 바꿨습니다.
@ManytoOne -> @OneToOne으로 바꿔야 됩니다. 실제 배포시
> [fix] 채널을 삭제하거나 채널멤버를 삭제시 삭제가 안되는 오류가 있었습니다.

- src/main/java/com/dnd12th_4/pickitalki/controller/login2/KakaoUserInfoResponseDto.java
- src/main/java/com/dnd12th_4/pickitalki/domain/question/Question.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
> 질문 여러개 생성한거 복구 하겠습니다.

- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionController.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
> [refactor] : swagger 페이지네이션 hidden

- src/main/java/com/dnd12th_4/pickitalki/controller/question/dto/TodayQuestionResponse.java
- src/main/java/com/dnd12th_4/pickitalki/domain/channel/ChannelMember.java
- src/main/java/com/dnd12th_4/pickitalki/service/answer/AnswerService.java
- src/main/java/com/dnd12th_4/pickitalki/service/channel/ChannelService.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
1. 프론트 측에서 원하는 반환값을 추가하여 반환값을 조정했습니다.
2. 답변 작성시 반환값이 null 로 보이는 문제 해결
3.  방장이 나가면 다른 사람 방장 부여 
4. 방을 나가려고 하는데 방에 나혼자 있을 경우 그 방 자체를 없애게 구현
```
요청사항)
GET: /api/channels/{channelId}/questions/today
response 에 추가가 필요한 데이터
몇명의 답변했는지 (없으면 0)
데이터가 있는 경우 question 의 id
내가 이미 답변을 한 시그널인지 true, false
```
> [feat] Question 및 Answer 반환 값 조정

- src/main/java/com/dnd12th_4/pickitalki/domain/answer/Answer.java
- src/main/java/com/dnd12th_4/pickitalki/domain/question/Question.java
- src/main/resources/schema.sql
> [refactor] : 디비 변경

- src/main/java/com/dnd12th_4/pickitalki/common/config/CorsConfig.java
- src/main/resources/application.yml
- src/main/resources/schema.sql
> [refactor] : CorsConfig

- src/main/java/com/dnd12th_4/pickitalki/controller/channel/ChannelController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/member/MemberController.java
- src/main/java/com/dnd12th_4/pickitalki/domain/channel/ChannelMemberRepository.java
- src/main/java/com/dnd12th_4/pickitalki/service/channel/ChannelService.java
- src/main/resources/application.yml
- src/main/resources/schema.sql
> [fixed] : channelMember 정렬 적용 안된거 해결

- src/main/java/com/dnd12th_4/pickitalki/common/config/AppConfig.java
- src/main/java/com/dnd12th_4/pickitalki/service/channel/ChannelService.java
- src/main/resources/application.yml
> [Refactor] 오늘의 질문자 조회 시 isTodayQuestioner에 로그인한 회원과 동일여부 반환

- src/main/java/com/dnd12th_4/pickitalki/service/channel/ChannelService.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
save함수에 검증절차가 많아서 함수를 생성하여
validate 검증을 따로 분리했습니다.
> Fix today question 오늘의 질문자가 아닌데 질문작성이 되는 문제 해결

- src/main/java/com/dnd12th_4/pickitalki/controller/channel/ChannelController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/channel/dto/response/ChannelNameUpdateResponse.java
- src/main/java/com/dnd12th_4/pickitalki/domain/channel/Channel.java
- src/main/java/com/dnd12th_4/pickitalki/service/channel/ChannelService.java
> [feat] 채널명 변경 기능

- docker-compose.yml
- src/main/java/com/dnd12th_4/pickitalki/PickitalkiApplication.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/dto/QuestionResponse.java
- src/main/java/com/dnd12th_4/pickitalki/presentation/exceptionhandler/ApiExceptionHandler.java
- src/main/java/com/dnd12th_4/pickitalki/presentation/exceptionhandler/GlobalExceptionHandler.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
- src/main/resources/application.yml
1. 질문 조회시 응답의 개수도 포함
2. 서버,db 시간을 UTC로 관리
3. 500에러가 나면 로그 남기기
> [feat] 질문 조회시 응답의 개수도 포함

- src/main/java/com/dnd12th_4/pickitalki/controller/channel/ChannelController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/member/dto/MyChannelMemberResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionControllerEnums.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/dto/QuestionResponse.java
- src/main/java/com/dnd12th_4/pickitalki/domain/question/QuestionRepository.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
> [feat] 모든,나의,친구의 질문 조회 기능

- src/main/java/com/dnd12th_4/pickitalki/domain/question/QuestionRepository.java
> [fix] 탈퇴한 회원이 있는 채널의 질문 조회시 에러발생 해결

- src/main/java/com/dnd12th_4/pickitalki/controller/answer/dto/response/AnswerQuestionDTO.java
- src/main/java/com/dnd12th_4/pickitalki/controller/answer/dto/response/AnswerResponse.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/dto/QuestionResponse.java
- src/main/java/com/dnd12th_4/pickitalki/domain/channel/ChannelMember.java
- src/main/java/com/dnd12th_4/pickitalki/service/answer/AnswerService.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
> [Fix] 탈퇴한 사용자의 질문 조회 시 오류 수정 + 질문,응답의 조회 시 프로필 이미지 정보 추가

- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionControllerEnums.java
- src/main/java/com/dnd12th_4/pickitalki/domain/question/QuestionRepository.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
> [fix] : question Request 변수에 tab 추가

- src/main/java/com/dnd12th_4/pickitalki/controller/question/QuestionController.java
- src/main/java/com/dnd12th_4/pickitalki/controller/question/dto/QuestionOneResponse.java
- src/main/java/com/dnd12th_4/pickitalki/service/channel/ChannelService.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
> Fix today question

- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
> [fix] : question response question id 가 0인 문제 해결

- src/main/java/com/dnd12th_4/pickitalki/service/channel/ChannelService.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
> feat: 시간정보에 timezone 정보 추가

- src/main/java/com/dnd12th_4/pickitalki/domain/channel/Channel.java
- src/main/java/com/dnd12th_4/pickitalki/service/channel/ChannelService.java
> [fix] : random(0) 문제가 발생하여 예외처리 진행했습니다

- src/main/java/com/dnd12th_4/pickitalki/PickitalkiApplication.java
- src/main/java/com/dnd12th_4/pickitalki/common/converter/DateTimeUtil.java
- src/main/java/com/dnd12th_4/pickitalki/service/answer/AnswerService.java
- src/main/java/com/dnd12th_4/pickitalki/service/question/QuestionService.java
- src/main/resources/application.yml
> [fix] : 시간관련 된것을 모두 kst로 변환했습니다.

- src/main/java/com/dnd12th_4/pickitalki/domain/BaseEntity.java
- src/main/java/com/dnd12th_4/pickitalki/domain/question/Question.java
> [fix] : BaseEntity 에서 강제로 KST로 변환하여 저장
